# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CESNET.
#
# Invenio OARepo is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

dist: xenial

addons:
  postgresql: "9.6"
  # TODO: Add mysql addon as well

services:
  - mysql

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  global:
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
    - ES_HOST=127.0.0.1
    - POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
    - MYSQL_SQLALCHEMY_DATABASE_URI="mysql://root@localhost/invenio"
  matrix:
    - REQUIREMENTS=release EXTRAS=all,elasticsearch6,postgresql ES_URL=$ES6_DOWNLOAD_URL SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release EXTRAS=all,elasticsearch6,sqlite ES_URL=$ES6_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,elasticsearch6,mysql ES_URL=$ES6_DOWNLOAD_URL SQLALCHEMY_DATABASE_URI=$MYSQL_SQLALCHEMY_DATABASE_URI

python:
  - "3.6"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"


install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls


deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "AWhOa2r5JSRsI79mo2dnHZAP5Ukq8wFl4DvN9CpvnDlvxSVoV3xcOPU3gn0Xb2Pt7wlH3sA9rWMrOix/iOwWwly2dWKgICL0t+Hm/thI/hKsw1rIHftgHxXIDCI2RVBIXMGBccJKr/XX+srPPNvgJDFJNJRnoSMeTF3wXVIydT61Fug39ixLECnfLBy686AoZBtCf42fHhq2kdsSs1B5mfNnnK6PJ5MKyqWYcYnTOr+nGYVK/GfYQ40Z7DimCHtxcMJKLCP7vHN/MYUxGMlB6DtROBUNSjg8TbW94EzUx3PSWjlqzLDtD3jRXNbQ2KRIxNpYZWiMKRrAThryzafWYf5yjg9aObnd+x3Dkmei65ykYDoRV4JuODFK/ifKDfA+aggPtalZ+ks8QDXJBQPH/B6+wImZ2WGt6+BzvEU5xMNm/f2hsQL5FtB+Dq+P0GOHonBJ5EMsRsqJNyDumsBxn1/p5vwm0auUYjWBWoDnb/vQShADlGjlQscXE+ev26wf8Wt1Wqi9EDQM23BV1aGSB68E4/SgecSxr43g2SUhVjtVgmtNdGJyWvNtLiofcX3gzz5/WiCryDh+OWPYk1jQYAQ8WqKQU26yZ7b+Mih+NsBDdLv5jMUfkiawrJ+tu50isywcSMGRfkkml5BBvOl4KvbEvbAVqO+iAORociHhGDc="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true

